#!/usr/bin/env python3
"""Download UCD property files and generate textseg/_data.py.

Data source: https://www.unicode.org/Public/<VERSION>/ucd/...
The generated tables are plain (start, end) inclusive range tuples,
merged and sorted, plus a version stamp.  No runtime segmentation
facility is used anywhere; these are raw Unicode data tables.
"""
import os
import sys
import urllib.request

VERSION = "16.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROPERTY_FILES = {
    "GraphemeBreakProperty.txt": "auxiliary/GraphemeBreakProperty.txt",
    "WordBreakProperty.txt": "auxiliary/WordBreakProperty.txt",
    "SentenceBreakProperty.txt": "auxiliary/SentenceBreakProperty.txt",
    "emoji-data.txt": "emoji/emoji-data.txt",
    "DerivedCoreProperties.txt": "DerivedCoreProperties.txt",
}

TEST_FILES = {
    "GraphemeBreakTest.txt": "auxiliary/GraphemeBreakTest.txt",
    "WordBreakTest.txt": "auxiliary/WordBreakTest.txt",
    "SentenceBreakTest.txt": "auxiliary/SentenceBreakTest.txt",
}


def download(url, dest):
    print(f"  GET {url}")
    with urllib.request.urlopen(url, timeout=60) as resp:
        data = resp.read()
    with open(dest, "wb") as fh:
        fh.write(data)
    return data


def parse_property_file(text, only_property=None):
    """Return {value: [(start, end), ...]} from a UCD property file.

    If only_property is given, keep only lines whose second field matches
    (3-field derived files such as DerivedCoreProperties.txt)."""
    table = {}
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        if only_property is not None:
            if len(fields) < 3 or fields[1] != only_property:
                continue
            rng, value = fields[0], fields[2]
        else:
            rng, value = fields[0], fields[1]
        if ".." in rng:
            lo, hi = rng.split("..")
        else:
            lo = hi = rng
        span = (int(lo, 16), int(hi, 16))
        table.setdefault(value, []).append(span)
    return table


def merge(ranges):
    out = []
    for lo, hi in sorted(ranges):
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def emit_table(fh, name, table):
    fh.write(f"{name} = {{\n")
    for value in sorted(table):
        ranges = merge(table[value])
        body = ", ".join(f"(0x{lo:X}, 0x{hi:X})" for lo, hi in ranges)
        fh.write(f"    {value!r}: ({body},),\n")
    fh.write("}\n\n")


def main():
    cache = os.path.join(ROOT, "tools", "ucd_cache")
    os.makedirs(cache, exist_ok=True)

    parsed = {}
    for fname, rel in PROPERTY_FILES.items():
        path = os.path.join(cache, fname)
        if not os.path.exists(path):
            download(f"{BASE}/{rel}", path)
        with open(path, encoding="utf-8") as fh:
            only = "InCB" if fname == "DerivedCoreProperties.txt" else None
            parsed[fname] = parse_property_file(fh.read(), only_property=only)

    test_dir = os.path.join(ROOT, "tests", "data")
    os.makedirs(test_dir, exist_ok=True)
    for fname, rel in TEST_FILES.items():
        path = os.path.join(test_dir, fname)
        if not os.path.exists(path):
            download(f"{BASE}/{rel}", path)

    out = os.path.join(ROOT, "textseg", "_data.py")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write('"""GENERATED by tools/gen_tables.py -- do not edit.\n\n')
        fh.write(f'Unicode data version: {VERSION}\n')
        fh.write('Range tables: (start, end) inclusive code-point ranges, sorted.\n')
        fh.write('"""\n\n')
        fh.write(f"UNICODE_VERSION = {VERSION!r}\n\n")
        emit_table(fh, "GCB", parsed["GraphemeBreakProperty.txt"])
        emit_table(fh, "WB", parsed["WordBreakProperty.txt"])
        emit_table(fh, "SB", parsed["SentenceBreakProperty.txt"])
        emit_table(fh, "INCB", parsed["DerivedCoreProperties.txt"])
        emoji = parsed["emoji-data.txt"]
        emit_table(fh, "EMOJI", {"Extended_Pictographic": emoji["Extended_Pictographic"]})
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
